[build-system]

requires = ["setuptools>=45", "wheel"]

build-backend = "setuptools.build_meta"



[project]

name = "credit_risk_probability_model_for_alternative_data"

version = "0.1.0"

description = ""

requires-python = ">=3.8"



[tool.setuptools.packages.find]

where = ["src"]

